apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "user-mgmt.selectorLabels" "backend" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-mgmt.selectorLabels" "backend" | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.images.backend }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-mgmt.selectorLabels" "backend" | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
