apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.db.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      {{- include "user-mgmt.selectorLabels" "db" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-mgmt.selectorLabels" "db" | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef: { name: app-config, key: POSTGRES_USER }
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef: { name: app-config, key: POSTGRES_DB }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: app-secret, key: SPRING_DATASOURCE_PASSWORD }
          volumeMounts:
            - name: db-storage
              mountPath: {{ .Values.db.mountPath }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-mgmt.selectorLabels" "db" | nindent 4 }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
