apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "user-mgmt.selectorLabels" "frontend" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-mgmt.selectorLabels" "frontend" | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEXT_PUBLIC_API_URL
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-mgmt.selectorLabels" "frontend" | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
