apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
