apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-probes
      match:
        resources:
          kinds: [Pod]
      validate:
        message: "livenessProbe und readinessProbe sind erforderlich."
        pattern:
          spec:
            containers:
              - livenessProbe: "?*"
                readinessProbe: "?*"
