prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

alertmanager:
  enabled: true

  createConfigMap: false

  extraVolumes:
    - name: ntfy-secret
      secret:
        secretName: ntfy-token
  extraMounts:
    - name: ntfy-secret
      mountPath: '/etc/alertmanager/secrets'
      readOnly: true

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  sidecar:
    dashboards:
      provider:
        foldersFromFilesStructure: true